### PR TITLE
Attachment fix

### PR DESCRIPTION
**Pull request by irosenb**
Should fix the [problem](https://heroku.honeybadger.io/projects/37452/faults/11738727)

### CODE REVIEW

**Comment by dinshaw** [comment]
Need a failing spec to expose the bug. For html stuff like this, a feature that ensures this page renders is sufficient.

**Comment by irosenb** [comment]
@dinshaw :white_check_mark:

**Comment by dinshaw** [comment]
Although clever, that still doesn't ensure that this page renders successfully.
Once a page makes it to production with a 500, it needs a spec around the render.
I'm guessing there already is one for admin/user/show, but maybe not with a populated business account.

**Comment by irosenb** [comment]
Changed. Thoughts @dinshaw ?

**Comment by dinshaw** [comment]
in the spirit of red, green, refactor, please confirm that that spec failed without your fix.

**Comment by irosenb** [comment]
@dinshaw haven't been successful in making the test fail. I'm trying to piggyback off the `features/admin/users_spec` but even with an attachment it doesn't fail…

**Comment by dinshaw** [comment]
If you revert your change, then the test should fail. if it doesn't, then
you either you didn't fix it, or you are testing the wrong thing, no?

**Comment by irosenb** [comment]
The problem is that Active Admin for some reason doesn't recognize that
there's a file attached…

**Comment by dinshaw** [comment]
Hen how was it generating a 500?

Sent via thousands of miles of curved space-time. 

On Mar 21, 2015, at 17:39, Isaac Rosenberg <notifications@github.com> wrote:

The problem is that Active Admin for some reason doesn't recognize that
there's a file attached…

**Comment by irosenb** [comment]
Meant that when I'm running the `admin/users_spec`, even though I can see that the user has a business with an attachment, Active Admin doesn't recognize that within the context of the tests. It's weird. 

Perhaps I'll ask a question on StackOverFlow.

**Comment by dinshaw** [comment]
we can pair up later today or tomorrow and figure it out.

**Comment by irosenb** [comment]
@dinshaw now good for merging

**Pull request merged**
