### PR TITLE
Hotfix

### PR DESCRIPTION
**Pull request by irosenb**
Missed a parameter for sending an email. This is a fix.

### CODE REVIEW

**Comment by dinshaw** [comment]
Needs a spec.

**Comment by irosenb** [comment]
@dinshaw done

**Comment by dinshaw** [comment]
Look good. May have been easier to do with a  mock 
```
expect(UserNotifier).to receive(:send_adg_email).with(current_user)
```

**Comment by irosenb** [comment]
Ahhh I see.

**Pull request merged**
